import { normalizeLocale } from '../i18n/index.js';

const ACCOUNT_CONTENT = {
  'zh-CN': {
    home: {
      eyebrow: '账户中心',
      title: '把消息、支持与信任控制收进一个地方',
      subtitle: '从通知、反馈到隐私说明、导出申请和删除申请，这里是 MintBit 的统一账户平台入口。',
      cards: [
        {
          id: 'messages',
          title: '消息中心',
          body: '查看系统通知、社区互动和打卡提醒，并管理未读状态。',
          cta: '进入消息中心',
          href: '/pages/profile/notifications/index',
        },
        {
          id: 'help',
          title: '帮助与支持',
          body: '查看 FAQ、联系支持、提交反馈并跟踪处理进度。',
          cta: '进入帮助中心',
          href: '/pages/profile/help/index',
        },
        {
          id: 'privacy',
          title: '隐私与权限',
          body: '查看协议、OCR 数据说明、社区可见性与通知权限。',
          cta: '进入隐私中心',
          href: '/pages/profile/privacy/index',
        },
        {
          id: 'data',
          title: '数据与审计',
          body: '发起导出、删除申请，并查看关键操作留痕说明。',
          cta: '查看数据控制',
          href: '/pages/profile/privacy/export/index',
        },
        {
          id: 'preferences',
          title: '账户与偏好',
          body: '管理账号绑定状态、OCR 授权、语言与通知偏好。',
          cta: '查看账户设置',
          href: '/pages/profile/security/index',
        },
      ],
      adminToolsCard: {
        id: 'admin',
        title: '发布检查',
        body: '仅管理员可见，查看当前版本、运行时状态、合规入口与平台预留检查项。',
        cta: '进入检查页',
        href: '/pages/profile/admin/release-checklist/index',
      },
      summary: {
        unreadLabel: '未读消息',
        feedbackLabel: '处理中反馈',
        exportLabel: '导出状态',
        deleteLabel: '删除申请',
        withdrawHint: '可撤回',
      },
    },
    notificationsView: {
      eyebrow: '消息中心',
      title: '把系统通知、社区互动和打卡提醒分开管理',
      subtitle: '支持分类查看、批量已读，以及进入每一条通知的详细上下文。',
      batchRead: '批量标记已读',
      emptyTitle: '当前筛选下没有消息',
      emptyBody: '切换筛选条件，或稍后回来看新的系统通知、社区互动和打卡提醒。',
      filters: {
        all: '全部',
        system: '系统通知',
        community: '社区互动',
        checkin: '打卡提醒',
      },
    },
    notificationDetail: {
      backCta: '返回消息中心',
      sourceLabel: '消息来源',
      timeLabel: '发送时间',
      relatedActionCta: '查看相关页面',
      autoReadHint: '打开详情后会自动记为已读。',
    },
    notifications: [
      {
        id: 'notif-1',
        type: 'system',
        status: 'unread',
        title: '你的数据导出包已开始生成',
        preview: '系统已受理导出请求，生成完成后会在账户中心提醒你。',
        body: '我们已经收到你的导出请求，当前状态为生成中。完成后你可以回到账户中心查看下载方式与有效期。',
        relativeTime: '10 分钟前',
        actionHref: '/pages/profile/privacy/export/index',
      },
      {
        id: 'notif-2',
        type: 'community',
        status: 'unread',
        title: '你的帖子审核状态已更新',
        preview: '压力恢复圈中的一条帖子从审核中更新为已通过。',
        body: '你在压力恢复圈发布的进展动态已通过审核，现在已经可以在公开社区中被其他用户看到。',
        relativeTime: '35 分钟前',
        actionHref: '/pages/community/my-posts/index',
      },
      {
        id: 'notif-3',
        type: 'checkin',
        status: 'read',
        title: '今天的打卡提醒已准备好',
        preview: '建议在晚饭后 30 分钟完成今天的补充记录。',
        body: '根据你当前的计划节奏，系统建议你在晚饭后 30 分钟内完成今天的补充打卡，这样更有利于持续跟踪。',
        relativeTime: '今天',
        actionHref: '/pages/checkin/index/index',
      },
    ],
    helpCenter: {
      eyebrow: '帮助与支持',
      title: '在账户中心里处理说明、反馈与支持入口',
      subtitle: '这里承接 FAQ、支持联系入口、反馈提交，以及反馈记录状态追踪。',
      faqTitle: '常见问题',
      backCta: '返回帮助中心',
      supportLabel: '支持邮箱',
      supportValue: 'support@mintbit.health',
      feedbackCta: '提交反馈',
      feedbackRecordsCta: '查看反馈记录',
    },
    feedbackForm: {
      title: '提交反馈',
      subtitle: '告诉我们你在问卷、报告、OCR、打卡、社区或账户中心里遇到的问题。',
      categoryLabel: '问题分类',
      subjectLabel: '反馈主题',
      subjectPlaceholder: '一句话概括问题或建议',
      descriptionLabel: '详细描述',
      descriptionPlaceholder: '描述触发路径、现象、你的预期结果，以及是否稳定复现。',
      contactLabel: '联系方式',
      contactPlaceholder: '邮箱、手机号或企业微信，便于后续联系',
      screenshotLabel: '截图占位',
      screenshotPlaceholder: '填写截图文件名或备注，本阶段先不做真实上传',
      submitCta: '提交反馈',
      successTitle: '反馈已提交',
      successBody: '你可以在反馈记录页查看后续状态变化和回复内容。',
      categories: ['问卷评估', '报告与画报', 'OCR 识别', '打卡体验', '社区互动', '通知体验', '账户与隐私'],
    },
    feedbackRecordsView: {
      title: '反馈记录',
      subtitle: '按状态查看你提交过的反馈，跟踪处理进度与回复内容。',
      emptyTitle: '还没有反馈记录',
      emptyBody: '当你提交第一条反馈后，这里会展示它的状态变化和官方回复。',
      groupTitles: {
        draft: '草稿',
        submitted: '已提交',
        in_review: '处理中',
        responded: '已回复',
        closed: '已关闭',
      },
    },
    feedbackRecords: [
      {
        id: 'fb-1',
        category: 'OCR 识别',
        subject: '报告页的 OCR 字段想要手动排序',
        status: 'in_review',
        submittedAt: '2026-03-15 18:20',
        description: '希望在 OCR 确认页里支持字段拖拽排序，减少手动核对成本。',
        contact: 'mintbit@example.com',
        screenshotName: 'ocr-order.png',
        reply: '团队已收到，正在评估表单排序能力。',
      },
      {
        id: 'fb-2',
        category: '通知体验',
        subject: '希望把社区互动和系统通知拆开',
        status: 'responded',
        submittedAt: '2026-03-14 10:12',
        description: '当前通知流缺少分类切换，希望按系统通知、社区互动和打卡提醒拆开。',
        contact: 'mintbit@example.com',
        reply: '已纳入账户中心平台化节点。',
      },
    ],
    privacyCenter: {
      title: '隐私、权限与数据控制',
      subtitle: '查看协议、OCR 使用说明、社区可见性、通知权限，以及导出和删除申请入口。',
      notificationPrefsLabel: '当前通知权限',
      securityCta: '查看安全与偏好',
      exportCta: '发起数据导出',
      deleteCta: '发起删除申请',
      auditCta: '查看留痕说明',
    },
    exportCenter: {
      title: '数据导出申请',
      subtitle: '导出入口覆盖评估、OCR、打卡和社区记录摘要。本阶段以用户可见状态流为准。',
      scopeLabel: '导出范围说明',
      scopePlaceholder: '描述要导出的数据范围',
      requestCta: '发起导出申请',
      activeLabel: '当前进行中的请求',
      emptyTitle: '还没有导出申请',
      emptyBody: '提交第一条导出申请后，这里会展示状态变化与范围说明。',
      defaultScopeSummary: '评估记录、OCR 补录、打卡记录、社区记录摘要',
    },
    deleteCenter: {
      title: '删除申请',
      subtitle: '删除申请会保留用户可见状态留痕，用于说明冷静期、确认和执行结果。',
      impactLabel: '影响范围说明',
      impactPlaceholder: '说明希望删除的数据范围',
      requestCta: '提交删除申请',
      emptyTitle: '还没有删除申请',
      emptyBody: '提交后这里会展示申请状态、时间和影响范围。',
      withdrawLabel: '当前申请仍可撤回',
    },
    exportRequests: [
      {
        id: 'export-1',
        requestedAt: '2026-03-16T09:30:00.000Z',
        status: 'generating',
        scopeSummary: '评估记录、OCR 补录、打卡记录、社区记录摘要',
      },
    ],
    deleteRequests: [
      {
        id: 'delete-1',
        status: 'cooling_off',
        submittedAt: '2026-03-16 09:45',
        impactSummary: '删除账户、评估记录、OCR 补录、打卡记录与社区可见资料',
      },
    ],
    securityView: {
      title: '安全与账户偏好',
      subtitle: '集中查看绑定状态、OCR 授权与通知偏好，作为企业微信和 Web 扩展前的统一账户快照。',
      bindingLabel: '账号绑定状态',
      ocrLabel: 'OCR 授权状态',
      notificationLabel: '通知偏好',
      enabledLabel: '已开启',
      disabledLabel: '已关闭',
    },
    auditView: {
      title: '审核与操作留痕',
      subtitle: '这里展示用户可见的请求留痕和平台透明说明，不是内部运营后台。',
      trailTitle: '最近可见留痕',
    },
    faqCategories: [
      {
        id: 'assessment',
        title: '评估与报告',
        items: [
          {
            question: '为什么报告页和 OCR 补录会同时存在？',
            answer: '问卷是基础输入，OCR 补录用于增强已有体检信息，两者结合后系统会输出更完整的解释。',
          },
        ],
      },
      {
        id: 'privacy',
        title: '隐私与数据',
        items: [
          {
            question: '导出请求会包含哪些数据？',
            answer: 'Phase 1 的导出说明覆盖评估记录、OCR 补录、打卡记录以及社区记录摘要。',
          },
        ],
      },
    ],
    documents: {
      privacyPolicy: {
        title: '隐私政策',
        body: [
          'MintBit 在 Phase 1 中收集问卷、可选 OCR 补录、打卡记录和社区互动数据，用于生成可解释的个性化营养体验。',
          '平台会明确区分系统生成内容、用户手动输入内容和用户授权上传内容。',
        ],
      },
      userAgreement: {
        title: '用户协议',
        body: [
          '账户中心中的通知、反馈、导出和删除申请均以用户当前登录身份为准。',
          '用户提交的反馈和删除申请会保留状态留痕，用于后续处理与追踪。',
        ],
      },
      ocrUsage: {
        title: 'OCR 数据使用说明',
        body: [
          'OCR 补录仅用于增强你自己的营养解释和后续追踪，不直接对外公开。',
          '用户可在账户中心查看 OCR 使用说明和授权状态。',
        ],
      },
      communityVisibility: {
        title: '社区可见性说明',
        body: [
          '社区中的公开帖子和评论会经过审核后展示。',
          '账户中心只说明可见性和审核规则，不提供绕过审核的控制项。',
        ],
      },
      auditLog: {
        title: '审核与操作留痕说明',
        body: [
          '为保证用户信任与请求可追踪，平台会对导出申请、删除申请、反馈记录和部分审核状态更新保留用户可见摘要。',
          '该页面展示的是透明说明和摘要，不是内部后台日志系统。',
        ],
      },
    },
    security: {
      accountBinding: 'unbound',
      ocrAuthorization: 'granted',
      notificationPreferences: {
        system: true,
        community: true,
        checkin: false,
      },
    },
    labels: {
      status: {
        draft: '草稿',
        submitted: '已提交',
        in_review: '处理中',
        responded: '已回复',
        closed: '已关闭',
        idle: '未发起',
        requested: '已申请',
        generating: '生成中',
        ready: '已就绪',
        expired: '已过期',
        failed: '失败',
        cooling_off: '冷静期中',
        confirmed: '已确认',
        executed: '已执行',
        rejected: '已驳回',
      },
      notificationTypes: {
        system: '系统通知',
        community: '社区互动',
        checkin: '打卡提醒',
      },
      notificationStatus: {
        unread: '未读',
        read: '已读',
        archived: '已归档',
      },
      accountBindingStatus: {
        bound: '已绑定',
        unbound: '未绑定',
        risk_notice: '风险提醒',
      },
      ocrAuthorizationStatus: {
        granted: '已授权',
        revoked: '已撤销',
      },
      sections: {
        messages: '消息中心',
        help: '帮助与支持',
        privacy: '隐私与权限',
        data: '数据与审计',
        preferences: '账户与偏好',
      },
    },
  },
  en: {
    home: {
      eyebrow: 'Account center',
      title: 'Keep messages, support, and trust controls in one place',
      subtitle: 'From notifications and feedback to privacy documents, export requests, and deletion requests, this is the unified MintBit account platform entry.',
      cards: [
        {
          id: 'messages',
          title: 'Messages',
          body: 'Review system notifications, community interactions, and check-in reminders while managing unread state.',
          cta: 'Open notifications',
          href: '/pages/profile/notifications/index',
        },
        {
          id: 'help',
          title: 'Help and support',
          body: 'Read FAQs, contact support, submit feedback, and track handling progress.',
          cta: 'Open help center',
          href: '/pages/profile/help/index',
        },
        {
          id: 'privacy',
          title: 'Privacy and permissions',
          body: 'Review policies, OCR data usage, community visibility, and notification permissions.',
          cta: 'Open privacy center',
          href: '/pages/profile/privacy/index',
        },
        {
          id: 'data',
          title: 'Data and audit',
          body: 'Start export or deletion requests and review key operation transparency notes.',
          cta: 'Review data controls',
          href: '/pages/profile/privacy/export/index',
        },
        {
          id: 'preferences',
          title: 'Account and preferences',
          body: 'Manage binding status, OCR authorization, language, and notification preferences.',
          cta: 'Review account settings',
          href: '/pages/profile/security/index',
        },
      ],
      adminToolsCard: {
        id: 'admin',
        title: 'Release checklist',
        body: 'Administrator-only diagnostics for version state, runtime status, compliance entry checks, and platform-readiness gates.',
        cta: 'Open release checks',
        href: '/pages/profile/admin/release-checklist/index',
      },
      summary: {
        unreadLabel: 'Unread',
        feedbackLabel: 'Open feedback',
        exportLabel: 'Export status',
        deleteLabel: 'Delete request',
        withdrawHint: 'Withdraw available',
      },
    },
    notificationsView: {
      eyebrow: 'Notifications',
      title: 'Separate system notices, community interactions, and check-in reminders',
      subtitle: 'Filter by stream, mark items read in batch, and open each notification for full context.',
      batchRead: 'Mark selected stream as read',
      emptyTitle: 'No messages in this filter',
      emptyBody: 'Switch filters or check back later for new system notices, community interactions, and check-in reminders.',
      filters: {
        all: 'All',
        system: 'System',
        community: 'Community',
        checkin: 'Check-in',
      },
    },
    notificationDetail: {
      backCta: 'Back to notifications',
      sourceLabel: 'Source',
      timeLabel: 'Sent at',
      relatedActionCta: 'Open related page',
      autoReadHint: 'Opening the detail will automatically mark it as read.',
    },
    notifications: [
      {
        id: 'notif-1',
        type: 'system',
        status: 'unread',
        title: 'Your data export package has started generating',
        preview: 'The export request is accepted. You will see another reminder here when it is ready.',
        body: 'We have received your export request and it is currently generating. When it is ready, return to the account center to review the delivery method and expiration window.',
        relativeTime: '10m ago',
        actionHref: '/pages/profile/privacy/export/index',
      },
      {
        id: 'notif-2',
        type: 'community',
        status: 'unread',
        title: 'Your post moderation status has changed',
        preview: 'One post in the Stress reset circle moved from pending to approved.',
        body: 'Your progress post in the Stress reset circle has been approved and is now visible in the public community feed.',
        relativeTime: '35m ago',
        actionHref: '/pages/community/my-posts/index',
      },
      {
        id: 'notif-3',
        type: 'checkin',
        status: 'read',
        title: 'Today\'s check-in reminder is ready',
        preview: 'The current plan suggests logging today\'s intake about 30 minutes after dinner.',
        body: 'Based on your current plan rhythm, the system suggests finishing today\'s supplement check-in within 30 minutes after dinner for steadier tracking.',
        relativeTime: 'Today',
        actionHref: '/pages/checkin/index/index',
      },
    ],
    helpCenter: {
      eyebrow: 'Help and support',
      title: 'Handle guidance, support, and feedback inside the account center',
      subtitle: 'This area holds FAQs, a support contact entry, feedback submission, and feedback-status tracking.',
      faqTitle: 'FAQs',
      backCta: 'Back to help center',
      supportLabel: 'Support email',
      supportValue: 'support@mintbit.health',
      feedbackCta: 'Submit feedback',
      feedbackRecordsCta: 'Open feedback records',
    },
    feedbackForm: {
      title: 'Submit feedback',
      subtitle: 'Tell us what you ran into across assessment, report, OCR, check-in, community, or the account center.',
      categoryLabel: 'Issue category',
      subjectLabel: 'Feedback subject',
      subjectPlaceholder: 'Summarize the issue or request in one line',
      descriptionLabel: 'Detailed description',
      descriptionPlaceholder: 'Describe the trigger path, visible behavior, expected result, and whether the issue is reproducible.',
      contactLabel: 'Contact',
      contactPlaceholder: 'Email, phone number, or WeCom contact for follow-up',
      screenshotLabel: 'Screenshot placeholder',
      screenshotPlaceholder: 'Provide a screenshot filename or note; real upload is deferred in this phase',
      submitCta: 'Submit feedback',
      successTitle: 'Feedback submitted',
      successBody: 'Open the feedback records page later to follow status changes and replies.',
      categories: ['Assessment', 'Report and poster', 'OCR recognition', 'Check-in', 'Community', 'Notification experience', 'Account and privacy'],
    },
    feedbackRecordsView: {
      title: 'Feedback records',
      subtitle: 'Review the feedback you submitted and track status changes and replies by state.',
      emptyTitle: 'No feedback records yet',
      emptyBody: 'After you submit your first feedback item, this page will show its status changes and official replies.',
      groupTitles: {
        draft: 'Draft',
        submitted: 'Submitted',
        in_review: 'In review',
        responded: 'Responded',
        closed: 'Closed',
      },
    },
    feedbackRecords: [
      {
        id: 'fb-1',
        category: 'OCR recognition',
        subject: 'I want manual field ordering on the OCR confirmation page',
        status: 'in_review',
        submittedAt: '2026-03-15 18:20',
        description: 'I want drag-and-drop field ordering on the OCR confirmation page to reduce manual review time.',
        contact: 'mintbit@example.com',
        screenshotName: 'ocr-order.png',
        reply: 'The team has received this and is reviewing form-ordering support.',
      },
      {
        id: 'fb-2',
        category: 'Notification experience',
        subject: 'Please separate community interactions from system notices',
        status: 'responded',
        submittedAt: '2026-03-14 10:12',
        description: 'The current notification stream needs clearer separation between system notices, community interactions, and check-in reminders.',
        contact: 'mintbit@example.com',
        reply: 'This is included in the account-center platformization node.',
      },
    ],
    privacyCenter: {
      title: 'Privacy, permissions, and data controls',
      subtitle: 'Review policies, OCR usage, community visibility, notification permissions, plus export and deletion entry points.',
      notificationPrefsLabel: 'Current notification permissions',
      securityCta: 'Open security and preferences',
      exportCta: 'Start data export',
      deleteCta: 'Start deletion request',
      auditCta: 'Open transparency notes',
    },
    exportCenter: {
      title: 'Data export requests',
      subtitle: 'The export entry covers assessment, OCR, check-in, and community-record summaries. In this phase the visible status flow is the source of truth.',
      scopeLabel: 'Export scope summary',
      scopePlaceholder: 'Describe the data scope you want to export',
      requestCta: 'Create export request',
      activeLabel: 'Current active request',
      emptyTitle: 'No export requests yet',
      emptyBody: 'After you create your first export request, this page will show status changes and scope details.',
      defaultScopeSummary: 'Assessment history, OCR enrichment, check-in records, and community-record summary',
    },
    deleteCenter: {
      title: 'Deletion requests',
      subtitle: 'Deletion requests keep a user-visible status trail so cooling-off, confirmation, and execution outcomes stay transparent.',
      impactLabel: 'Impact summary',
      impactPlaceholder: 'Describe the data scope you want deleted',
      requestCta: 'Submit deletion request',
      emptyTitle: 'No deletion requests yet',
      emptyBody: 'After you submit one, this page will show its status, timestamp, and impact summary.',
      withdrawLabel: 'This request can still be withdrawn',
    },
    exportRequests: [
      {
        id: 'export-1',
        requestedAt: '2026-03-16T09:30:00.000Z',
        status: 'generating',
        scopeSummary: 'Assessment history, OCR enrichment, check-in records, and community-record summary',
      },
    ],
    deleteRequests: [
      {
        id: 'delete-1',
        status: 'cooling_off',
        submittedAt: '2026-03-16 09:45',
        impactSummary: 'Account profile, assessment history, OCR enrichment, check-in records, and visible community profile data',
      },
    ],
    securityView: {
      title: 'Security and account preferences',
      subtitle: 'Review binding status, OCR authorization, and notification preferences as the unified account snapshot before WeCom and Web expansion.',
      bindingLabel: 'Account binding',
      ocrLabel: 'OCR authorization',
      notificationLabel: 'Notification preferences',
      enabledLabel: 'Enabled',
      disabledLabel: 'Disabled',
    },
    auditView: {
      title: 'Audit and operation transparency',
      subtitle: 'This page shows user-visible request trails and transparency notes, not the internal operations console.',
      trailTitle: 'Recent visible trail',
    },
    faqCategories: [
      {
        id: 'assessment',
        title: 'Assessment and report',
        items: [
          {
            question: 'Why do the report page and OCR enrichment both exist?',
            answer: 'The questionnaire is the base input, while OCR enrichment strengthens it with past checkup data so the explanation can be more complete.',
          },
        ],
      },
      {
        id: 'privacy',
        title: 'Privacy and data',
        items: [
          {
            question: 'What data is included in an export request?',
            answer: 'Phase 1 export scope covers assessment history, OCR enrichment, check-in records, and community-record summaries.',
          },
        ],
      },
    ],
    documents: {
      privacyPolicy: {
        title: 'Privacy Policy',
        body: [
          'In Phase 1, MintBit collects questionnaire inputs, optional OCR enrichment, check-in history, and community interactions to generate an explainable personalized nutrition journey.',
          'The platform explicitly distinguishes system-generated content, user-entered content, and user-authorized uploads.',
        ],
      },
      userAgreement: {
        title: 'User Agreement',
        body: [
          'Notifications, feedback, export requests, and deletion requests in the account center all operate against the current signed-in account.',
          'Feedback submissions and deletion requests keep visible status trails for later handling and tracking.',
        ],
      },
      ocrUsage: {
        title: 'OCR Data Usage',
        body: [
          'OCR enrichment is only used to strengthen your own nutrition explanation and follow-up tracking. It is not published publicly.',
          'Users can review OCR usage notes and authorization state inside the account center.',
        ],
      },
      communityVisibility: {
        title: 'Community Visibility',
        body: [
          'Public community posts and comments only appear after moderation review.',
          'The account center explains visibility and moderation rules but does not expose controls that bypass moderation.',
        ],
      },
      auditLog: {
        title: 'Audit and Operation Transparency',
        body: [
          'To preserve user trust and request traceability, the platform keeps user-visible summaries for export requests, deletion requests, feedback records, and some moderation-state changes.',
          'This page is a transparency explanation with visible summaries, not an internal operations console.',
        ],
      },
    },
    security: {
      accountBinding: 'unbound',
      ocrAuthorization: 'granted',
      notificationPreferences: {
        system: true,
        community: true,
        checkin: false,
      },
    },
    labels: {
      status: {
        draft: 'Draft',
        submitted: 'Submitted',
        in_review: 'In review',
        responded: 'Responded',
        closed: 'Closed',
        idle: 'Idle',
        requested: 'Requested',
        generating: 'Generating',
        ready: 'Ready',
        expired: 'Expired',
        failed: 'Failed',
        cooling_off: 'Cooling-off',
        confirmed: 'Confirmed',
        executed: 'Executed',
        rejected: 'Rejected',
      },
      notificationTypes: {
        system: 'System',
        community: 'Community',
        checkin: 'Check-in',
      },
      notificationStatus: {
        unread: 'Unread',
        read: 'Read',
        archived: 'Archived',
      },
      accountBindingStatus: {
        bound: 'Bound',
        unbound: 'Unbound',
        risk_notice: 'Risk notice',
      },
      ocrAuthorizationStatus: {
        granted: 'Granted',
        revoked: 'Revoked',
      },
      sections: {
        messages: 'Messages',
        help: 'Help and support',
        privacy: 'Privacy and permissions',
        data: 'Data and audit',
        preferences: 'Account and preferences',
      },
    },
  },
};

export function getAccountContent(locale) {
  return ACCOUNT_CONTENT[normalizeLocale(locale)] || ACCOUNT_CONTENT['zh-CN'];
}

export { ACCOUNT_CONTENT };
