import { normalizeLocale } from '../i18n/index.js';

const COMMUNITY_CONTENT = {
  'zh-CN': {
    home: {
      title: '和同频的人一起坚持',
      subtitle: '围绕测评、打卡和日常反馈，把个人变化带回社区继续发生。',
      recommendedTab: '推荐',
      circlesTab: '圈子',
      allCircles: '全部',
      createCta: '发布动态',
      myPostsCta: '我的帖子',
      emptyTitle: '还没有公开动态',
      emptyBody: '先去发一条近况，让同阶段的人看到你的变化。',
      timelineBridge: {
        eyebrow: '历史画报联动',
        title: '把时间轴里的变化带回社区',
        body: '回顾最近的报告、OCR 补充和打卡进度，再看看相似目标的人都在怎么坚持。',
        cta: '查看历史时间轴',
      },
    },
    create: {
      title: '发布一条新的进展',
      subtitle: '描述今天的饮食、补充和体感变化，系统会先进入审核状态。',
      circleLabel: '选择圈子',
      contentLabel: '正文内容',
      contentPlaceholder: '例如：补充镁 14 天后，入睡速度明显更快，今天把晚间咖啡也停掉了。',
      tagsLabel: '建议标签',
      addImage: '添加图片',
      imageHint: 'Phase 1 先用占位图流程，不接真实上传存储。',
      submit: '提交审核',
      successTitle: '已提交审核',
      successBody: '你的帖子已进入审核队列，审核通过后会出现在公开社区。',
      pendingHint: '审核中内容仅你自己和运营可见。',
    },
    detail: {
      backCta: '返回社区',
      commentsTitle: '评论区',
      commentPlaceholder: '补充你的经验、提问或者鼓励',
      submitComment: '提交评论',
      noComments: '还没有评论，写下第一条反馈吧。',
      like: '点赞',
      save: '收藏',
    },
    myPosts: {
      title: '我的帖子',
      subtitle: '这里会展示你所有可见的审核状态，方便追踪每一条内容的进展。',
      tabs: {
        pending_review: '审核中',
        approved: '已通过',
        rejected: '未通过',
        flagged: '已标记',
      },
      emptyTitle: '这一栏还没有内容',
      emptyBody: '先回到社区发布一条更新。',
      resubmit: '编辑后重发',
    },
    review: {
      title: '社区审核',
      subtitle: '手机端快速处理待审帖子和评论。',
      tabs: {
        pending_review: '待审核',
        approved: '已通过',
        rejected: '已拒绝',
        flagged: '已标记',
      },
      targetPost: '帖子',
      targetComment: '评论',
      queueEmptyTitle: '当前队列已清空',
      queueEmptyBody: '切换其他状态看看最近处理记录。',
      actions: {
        approve: '通过',
        reject: '拒绝',
        flag: '标记',
        restore: '恢复',
      },
    },
    statuses: {
      draft: '草稿',
      pending_review: '审核中',
      approved: '已通过',
      rejected: '未通过',
      flagged: '已标记',
      hidden: '已隐藏',
    },
    circles: [
      {
        id: 'gut-balance',
        name: '肠胃平衡圈',
        description: '记录益生菌、纤维和作息调整后的体感变化。',
        members: 12680,
        accent: 'from-[#BFE4C8] to-[#6DB578]',
      },
      {
        id: 'stress-reset',
        name: '压力恢复圈',
        description: '围绕睡眠、情绪和恢复节奏互相打卡。',
        members: 9310,
        accent: 'from-[#DDE7A3] to-[#BFD46C]',
      },
      {
        id: 'movement-energy',
        name: '运动能量圈',
        description: '分享训练、恢复和营养补充的真实反馈。',
        members: 7842,
        accent: 'from-[#BFD8F5] to-[#78AEE8]',
      },
    ],
    seedPosts: [
      {
        id: 'post-101',
        authorName: '陈瑜',
        authorAvatar: '瑜',
        authorRole: '肠胃轻调理阶段',
        viewerOwned: false,
        circleId: 'gut-balance',
        circleName: '肠胃平衡圈',
        status: 'approved',
        relativeTime: '2 小时前',
        content: '第 12 天把早餐改成高蛋白加可溶性纤维之后，下午胀气明显少了，今天终于没有靠薄荷糖硬扛。',
        tags: ['益生菌', '纤维', '早餐'],
        images: [],
        likes: 42,
        saves: 18,
        comments: [
          {
            id: 'comment-101-1',
            authorName: '小雅',
            authorAvatar: '雅',
            authorRole: '粒子助手用户',
            viewerOwned: true,
            status: 'approved',
            relativeTime: '1 小时前',
            content: '我也是先从早餐改起，连续一周后胃口稳定很多。',
            likes: 8,
          },
        ],
      },
      {
        id: 'post-102',
        authorName: '小雅',
        authorAvatar: '雅',
        authorRole: '粒子助手用户',
        viewerOwned: true,
        circleId: 'stress-reset',
        circleName: '压力恢复圈',
        status: 'pending_review',
        relativeTime: '刚刚',
        content: '今天把晚上的镁补充提前到晚饭后，23:10 就有困意了，准备连续试 7 天再更新。',
        tags: ['镁', '睡眠', '节律'],
        images: [],
        likes: 0,
        saves: 0,
        comments: [
          {
            id: 'comment-102-1',
            authorName: '运营审核',
            authorAvatar: '审',
            authorRole: '系统状态',
            viewerOwned: false,
            status: 'pending_review',
            relativeTime: '刚刚',
            content: '评论内容待审核后展示。',
            likes: 0,
          },
        ],
      },
      {
        id: 'post-103',
        authorName: '小雅',
        authorAvatar: '雅',
        authorRole: '粒子助手用户',
        viewerOwned: true,
        circleId: 'movement-energy',
        circleName: '运动能量圈',
        status: 'rejected',
        relativeTime: '昨天',
        content: '连续三次力量训练前补充电解质，腿抽筋频率明显下降，但原文里把剂量写得太像明确疗效结论了。',
        tags: ['电解质', '训练恢复'],
        images: [],
        likes: 0,
        saves: 1,
        comments: [],
        moderationReason: '文案包含容易被理解为确定疗效的表达，请改为个人体验描述。',
      },
      {
        id: 'post-104',
        authorName: '小雅',
        authorAvatar: '雅',
        authorRole: '粒子助手用户',
        viewerOwned: true,
        circleId: 'gut-balance',
        circleName: '肠胃平衡圈',
        status: 'flagged',
        relativeTime: '2 天前',
        content: '出差时断了两天补充，今天重新开始记录餐后反应，先把这次波动单独记下来。',
        tags: ['出差', '复盘'],
        images: [],
        likes: 3,
        saves: 4,
        comments: [],
        moderationReason: '内容被运营标记为需要二次确认，请稍后查看处理结果。',
      },
    ],
    reviewQueue: [
      {
        id: 'queue-201',
        targetId: 'post-102',
        targetType: 'post',
        authorName: '小雅',
        authorAvatar: '雅',
        circleName: '压力恢复圈',
        currentStatus: 'pending_review',
        relativeTime: '刚刚',
        contentPreview: '今天把晚上的镁补充提前到晚饭后，23:10 就有困意了，准备连续试 7 天再更新。',
        moderationReason: '待人工确认是否包含敏感剂量暗示。',
      },
      {
        id: 'queue-202',
        targetId: 'comment-102-1',
        targetType: 'comment',
        authorName: '匿名用户',
        authorAvatar: '匿',
        circleName: '压力恢复圈',
        currentStatus: 'flagged',
        relativeTime: '10 分钟前',
        contentPreview: '这个补充剂是不是能直接治失眠？',
        moderationReason: '涉及明确治疗暗示，需要运营处理。',
      },
    ],
  },
  en: {
    home: {
      title: 'Stay consistent with people on the same path',
      subtitle: 'Carry assessment insights, check-ins, and daily body feedback back into the community loop.',
      recommendedTab: 'Recommended',
      circlesTab: 'Circles',
      allCircles: 'All',
      createCta: 'Create post',
      myPostsCta: 'My posts',
      emptyTitle: 'No public updates yet',
      emptyBody: 'Share a recent update so people at the same stage can see your progress.',
      timelineBridge: {
        eyebrow: 'Poster history bridge',
        title: 'Bring timeline progress back into the community',
        body: 'Review recent reports, OCR enrichments, and check-in milestones, then see how people with similar goals keep going.',
        cta: 'Open history timeline',
      },
    },
    create: {
      title: 'Share a new progress update',
      subtitle: 'Describe today\'s food, supplementation, and body feedback. The post enters review before it becomes public.',
      circleLabel: 'Choose a circle',
      contentLabel: 'Post content',
      contentPlaceholder: 'Example: after 14 days of magnesium, I fell asleep faster and I also stopped evening coffee today.',
      tagsLabel: 'Suggested tags',
      addImage: 'Add images',
      imageHint: 'Phase 1 keeps image upload as a placeholder flow without real storage.',
      submit: 'Submit for review',
      successTitle: 'Sent to review',
      successBody: 'Your post is now in the moderation queue and will appear in the public community after approval.',
      pendingHint: 'Pending content is only visible to you and the operations reviewer.',
    },
    detail: {
      backCta: 'Back to community',
      commentsTitle: 'Comments',
      commentPlaceholder: 'Share your experience, ask a question, or leave encouragement',
      submitComment: 'Post comment',
      noComments: 'No comments yet. Write the first response.',
      like: 'Like',
      save: 'Save',
    },
    myPosts: {
      title: 'My posts',
      subtitle: 'Track every visible moderation state here so each update has a clear next step.',
      tabs: {
        pending_review: 'Pending',
        approved: 'Approved',
        rejected: 'Rejected',
        flagged: 'Flagged',
      },
      emptyTitle: 'Nothing in this tab yet',
      emptyBody: 'Go back to the community and publish a new update.',
      resubmit: 'Edit and resubmit',
    },
    review: {
      title: 'Community review',
      subtitle: 'Process pending posts and comments from a phone-first moderation view.',
      tabs: {
        pending_review: 'Pending',
        approved: 'Approved',
        rejected: 'Rejected',
        flagged: 'Flagged',
      },
      targetPost: 'Post',
      targetComment: 'Comment',
      queueEmptyTitle: 'This queue is empty',
      queueEmptyBody: 'Switch tabs to review recent decisions.',
      actions: {
        approve: 'Approve',
        reject: 'Reject',
        flag: 'Flag',
        restore: 'Restore',
      },
    },
    statuses: {
      draft: 'Draft',
      pending_review: 'Pending',
      approved: 'Approved',
      rejected: 'Rejected',
      flagged: 'Flagged',
      hidden: 'Hidden',
    },
    circles: [
      {
        id: 'gut-balance',
        name: 'Gut balance',
        description: 'Track how probiotics, fiber, and routine changes affect your digestion.',
        members: 12680,
        accent: 'from-[#BFE4C8] to-[#6DB578]',
      },
      {
        id: 'stress-reset',
        name: 'Stress reset',
        description: 'Check in with each other around sleep, mood, and recovery rhythm.',
        members: 9310,
        accent: 'from-[#DDE7A3] to-[#BFD46C]',
      },
      {
        id: 'movement-energy',
        name: 'Movement energy',
        description: 'Share real feedback on training, recovery, and nutrition support.',
        members: 7842,
        accent: 'from-[#BFD8F5] to-[#78AEE8]',
      },
    ],
    seedPosts: [
      {
        id: 'post-101',
        authorName: 'Yu Chen',
        authorAvatar: 'Y',
        authorRole: 'Gut reset stage',
        viewerOwned: false,
        circleId: 'gut-balance',
        circleName: 'Gut balance',
        status: 'approved',
        relativeTime: '2h ago',
        content: 'On day 12, switching breakfast to higher protein plus soluble fiber finally reduced my afternoon bloating.',
        tags: ['Probiotics', 'Fiber', 'Breakfast'],
        images: [],
        likes: 42,
        saves: 18,
        comments: [
          {
            id: 'comment-101-1',
            authorName: 'Xiaoya',
            authorAvatar: 'X',
            authorRole: 'Particle assistant user',
            viewerOwned: true,
            status: 'approved',
            relativeTime: '1h ago',
            content: 'I also started with breakfast changes first, and my appetite stabilized after a week.',
            likes: 8,
          },
        ],
      },
      {
        id: 'post-102',
        authorName: 'Xiaoya',
        authorAvatar: 'X',
        authorRole: 'Particle assistant user',
        viewerOwned: true,
        circleId: 'stress-reset',
        circleName: 'Stress reset',
        status: 'pending_review',
        relativeTime: 'Just now',
        content: 'I moved magnesium to right after dinner today and felt sleepy by 11:10 PM. I want to track this for 7 days.',
        tags: ['Magnesium', 'Sleep', 'Rhythm'],
        images: [],
        likes: 0,
        saves: 0,
        comments: [
          {
            id: 'comment-102-1',
            authorName: 'Review status',
            authorAvatar: 'R',
            authorRole: 'System note',
            viewerOwned: false,
            status: 'pending_review',
            relativeTime: 'Just now',
            content: 'Comment content will appear after moderation.',
            likes: 0,
          },
        ],
      },
      {
        id: 'post-103',
        authorName: 'Xiaoya',
        authorAvatar: 'X',
        authorRole: 'Particle assistant user',
        viewerOwned: true,
        circleId: 'movement-energy',
        circleName: 'Movement energy',
        status: 'rejected',
        relativeTime: 'Yesterday',
        content: 'Electrolytes before my last three strength sessions reduced calf cramps, but the copy still sounded too much like a guaranteed result.',
        tags: ['Electrolytes', 'Recovery'],
        images: [],
        likes: 0,
        saves: 1,
        comments: [],
        moderationReason: 'The copy may be read as a definite efficacy claim. Rewrite it as a personal experience.',
      },
      {
        id: 'post-104',
        authorName: 'Xiaoya',
        authorAvatar: 'X',
        authorRole: 'Particle assistant user',
        viewerOwned: true,
        circleId: 'gut-balance',
        circleName: 'Gut balance',
        status: 'flagged',
        relativeTime: '2 days ago',
        content: 'I missed two days while traveling, so I restarted my meal-response notes and logged this fluctuation separately.',
        tags: ['Travel', 'Review'],
        images: [],
        likes: 3,
        saves: 4,
        comments: [],
        moderationReason: 'Operations flagged this content for a second review. Check back for the next status update.',
      },
    ],
    reviewQueue: [
      {
        id: 'queue-201',
        targetId: 'post-102',
        targetType: 'post',
        authorName: 'Xiaoya',
        authorAvatar: 'X',
        circleName: 'Stress reset',
        currentStatus: 'pending_review',
        relativeTime: 'Just now',
        contentPreview: 'I moved magnesium to right after dinner today and felt sleepy by 11:10 PM. I want to track this for 7 days.',
        moderationReason: 'Needs a human check for dosage-sensitive phrasing.',
      },
      {
        id: 'queue-202',
        targetId: 'comment-102-1',
        targetType: 'comment',
        authorName: 'Anonymous user',
        authorAvatar: 'A',
        circleName: 'Stress reset',
        currentStatus: 'flagged',
        relativeTime: '10m ago',
        contentPreview: 'Can this supplement directly cure insomnia?',
        moderationReason: 'Contains explicit treatment language and needs moderation.',
      },
    ],
  },
};

export function getCommunityContent(locale) {
  return COMMUNITY_CONTENT[normalizeLocale(locale)] || COMMUNITY_CONTENT['zh-CN'];
}

export { COMMUNITY_CONTENT };
